### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by KnorpelSenf** [Satont/grammy-redis-storage#2]
Please add a LICENSE file so people are allowed to use your code. Maybe use MIT?

**Comment by Satont** [comment]
I never dealing with licences actually. Should i include licence in the final package production build, or it leave it on github is fine?

**Comment by KnorpelSenf** [comment]
It makes sense to ship it.

Without a license, no one is allowed to use your code. That technically also means installing it from npm and using it in a bot. You need to explicitly grant people permission to do it in order for them to do it legally.

It is very easy to create a license by clicking New File on the GitHub website, and typing the file name LICENSE. Then you can click through different options and you're done. Literally takes seconds.

**Comment by Satont** [comment]
> It makes sense to ship it.

Ok.

> It is very easy to create a license by clicking New File on the GitHub website, and typing the file name LICENSE. Then you can click through different options and you're done. Literally takes seconds.

Actually i'l already created PR #4, just wasn't sure about shipping of that file. So, i'll add licence to `files`, and release new version.
